<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>6.2236.v12dd4c483242</version>
        <relativePath/>
    </parent>

    <artifactId>chatwork</artifactId>
    <name>ChatWork Plugin</name>
    <description>This Plugin will notify the ChatWork any message.</description>
    <version>1.0.11-SNAPSHOT</version>
    <packaging>hpi</packaging>
    <url>https://github.com/jenkinsci/chatwork-plugin</url>

    <scm>
        <connection>scm:git:https://github.com/jenkinsci/chatwork-plugin.git</connection>
        <developerConnection>scm:git:git@github.com:jenkinsci/chatwork-plugin.git</developerConnection>
        <url>https://github.com/jenkinsci/chatwork-plugin.git</url>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>vexus2</id>
            <name>vexus2</name>
            <email>hikaru.tooyama@gmail.com</email>
        </developer>
        <developer>
            <id>sue445</id>
            <name>sue445</name>
            <email>sue445@sue445.net</email>
        </developer>
    </developers>

    <properties>
        <jenkins.version>2.555.3</jenkins.version>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.555.x</artifactId>
                <version>7046.v43536164769c</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>jackson2-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
